### ISSUE TITLE
Need to define script for search algorithm

### ISSUE THREAD

**Issue by gslavin** [gslavin/ArchEval#1]
We need to create a script that will serve as the prototype for the search algorithm program.  This will use each of the simulation wrappers to run a variety of simulations.  The search program should do the following:

1) Parse user constraints and system configuration

2) Use user constraints to create permutations of the system configuration

3) Run each permutation of the system configuration on a set of simulators

4)  Aggregate the results from these simulators and evaluate the fitness of the configuration

5) Eliminate poorly performing configurations

6) Decide whether another round of permutations will be performed

7) Send the results of the final round to the visualization software

**Comment by ghost** [comment]
Hey, i'm starting to sketch this out now.

**Comment by ghost** [comment]
I'm putting my scratch work in a separate branch for now, we can merge in later.

**Comment by gslavin** [comment]
DSE_search has been merged into master.
